apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1
  version: "1.30"

# IAM OIDC & Service Accounts
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true

# VPC Configuration
vpc:
  enableDnsHostnames: true
  enableDnsSupport: true
  cidr: 10.0.0.0/16
  subnets:
    public:
      us-east-1a:
        cidr: 10.0.1.0/24
      us-east-1b:
        cidr: 10.0.2.0/24
      us-east-1c:
        cidr: 10.0.3.0/24
    private:
      us-east-1a:
        cidr: 10.0.11.0/24
      us-east-1b:
        cidr: 10.0.12.0/24
      us-east-1c:
        cidr: 10.0.13.0/24

# Managed Node Groups
managedNodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    minSize: 2
    maxSize: 5
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 20
    volumeType: gp3
    ssh:
      allow: true
    labels:
      role: worker
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/my-eks-cluster: "owned"
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

# Add-ons
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true

# CloudWatch Logging
cloudWatch:
  clusterLogging:
    enable: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    logRetentionInDays: 60

# Fargate Profiles (Optional)
fargateProfiles:
  - name: default
    selectors:
      - namespace: default
        labels:
          fargate: "true"
  - name: kube-system
    selectors:
      - namespace: kube-system