apiVersion: v1
kind: Pod
metadata:
  name: fargate-test-pod
  namespace: default
  labels:
    compute-type: fargate
    app: test-fargate
spec:
  containers:
  - name: test-container
    image: nginx:1.20
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always