apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: web-apps
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: httpd:2.4
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: COMPUTE_TYPE
          value: "fargate"
        - name: TIER
          value: "frontend"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: web-apps
spec:
  selector:
    app: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer